### ISSUE TITLE
Atlas integration

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Ulysses#14]
Add integration with Atlas via ROhdsiWebApi.

1. Establish "Atlas mode" for authentication with WebAPI - see https://ohdsi.github.io/ROhdsiWebApi/articles/authenticationSecurity.html for more info. 
2. If in Atlas mode, then when cohort ids are added to the yaml file, resolve these in building out the documentation:
  - ROhdsiWebApi::getCohortDefinition()
  - ROhdsiWebApi::getCohortDefinitionName()
  - ROhdsiWebApi::getCohortDefinitionsMetaData()
  - Use CirceR to resolve into print friendly

**Comment by mdlavallee92** [comment]
Add import cohort and concept set function....something to revisit with more helpers to work with ATLAs
