### ISSUE TITLE
Docs refer to makeConfig but should be initConfig?

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Ulysses#21]
Docs: https://ohdsi.github.io/Ulysses/articles/start_study.html#config-yml

makeConfig doesn't exist, but I checked and initConfig appears to serve this same purpose.

**Comment by mdlavallee92** [comment]
whoops...I forgot to change this in the docs. thanks for catching that. 

Follow allow this vignette to set up the config.yml file https://ohdsi.github.io/Ulysses/articles/credentials.html

**Comment by mdlavallee92** [comment]
Should be correct in v006 see #22 

Closing

**Comment by katy-sadowski** [comment]
Warning message for addConfig still refers to makeConfig
