### ISSUE TITLE
Bugs in ATLAS script

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/Ulysses#23]
https://github.com/OHDSI/Ulysses/blob/e1f093643e79607e7d98edea9b37091282a918a4/R/atlas.R#L92

Here and elsewhere in the script, it hardcodes the keyring name - should take the input param for keyringName instead.
Also, it hardcodes the name of the keyring entries as atlas_X although in the setup instructions it puts a prefix of webapi_ (https://ohdsi.github.io/Ulysses/articles/atlas.html#set-up-connection-with-atlas).  Should either align these, or include the "db" prefix as an input to the function.

**Comment by mdlavallee92** [comment]
Error also occurring during ingestion of circe cohorts. 

On (L48)[https://github.com/OHDSI/Ulysses/blob/main/R/atlas.R#L48] try to rearrange the json headers from webapi back to normal circe. This causes a circe error, invalid json string. 

Thanks @katy-sadowski for noticing this.
